packages:
  - 'apps/*'
  - 'packages/*'

# Catalog for shared dependencies
catalog:
  # Core dependencies
  react: ^18.2.0
  react-dom: ^18.2.0
  typescript: ^5.3.0
  vite: ^5.0.0
  
  # Backend dependencies
  fastify: ^4.24.0
  prisma: ^5.7.0
  '@prisma/client': ^5.7.0
  
  # Shared utilities
  zod: ^3.22.0
  '@clerk/clerk-js': ^4.70.0
  '@clerk/fastify': ^0.7.0
  
  # Development dependencies
  '@types/node': ^20.10.0
  '@types/react': ^18.2.0
  '@types/react-dom': ^18.2.0
  eslint: ^8.55.0
  prettier: ^3.1.0
  vitest: ^1.0.0